#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xbitmaps
Version  : 1.1.2
Release  : 4
URL      : https://www.x.org/releases/individual/data/xbitmaps-1.1.2.tar.gz
Source0  : https://www.x.org/releases/individual/data/xbitmaps-1.1.2.tar.gz
Summary  : Bitmaps that are shared between X applications
Group    : Development/Tools
License  : HPND ICU
BuildRequires : pkgconfig(xorg-macros)

%description
No detailed description available

%package dev
Summary: dev components for the xbitmaps package.
Group: Development
Provides: xbitmaps-devel

%description dev
dev components for the xbitmaps package.


%prep
%setup -q -n xbitmaps-1.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1520782408
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1520782408
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/bitmaps/1x1
/usr/include/X11/bitmaps/2x2
/usr/include/X11/bitmaps/black
/usr/include/X11/bitmaps/black6
/usr/include/X11/bitmaps/box6
/usr/include/X11/bitmaps/boxes
/usr/include/X11/bitmaps/calculator
/usr/include/X11/bitmaps/cntr_ptr
/usr/include/X11/bitmaps/cntr_ptrmsk
/usr/include/X11/bitmaps/cross_weave
/usr/include/X11/bitmaps/dimple1
/usr/include/X11/bitmaps/dimple3
/usr/include/X11/bitmaps/dot
/usr/include/X11/bitmaps/dropbar7
/usr/include/X11/bitmaps/dropbar8
/usr/include/X11/bitmaps/escherknot
/usr/include/X11/bitmaps/flagdown
/usr/include/X11/bitmaps/flagup
/usr/include/X11/bitmaps/flipped_gray
/usr/include/X11/bitmaps/gray
/usr/include/X11/bitmaps/gray1
/usr/include/X11/bitmaps/gray3
/usr/include/X11/bitmaps/grid16
/usr/include/X11/bitmaps/grid2
/usr/include/X11/bitmaps/grid4
/usr/include/X11/bitmaps/grid8
/usr/include/X11/bitmaps/hlines2
/usr/include/X11/bitmaps/hlines3
/usr/include/X11/bitmaps/icon
/usr/include/X11/bitmaps/keyboard16
/usr/include/X11/bitmaps/left_ptr
/usr/include/X11/bitmaps/left_ptrmsk
/usr/include/X11/bitmaps/letters
/usr/include/X11/bitmaps/light_gray
/usr/include/X11/bitmaps/mailempty
/usr/include/X11/bitmaps/mailemptymsk
/usr/include/X11/bitmaps/mailfull
/usr/include/X11/bitmaps/mailfullmsk
/usr/include/X11/bitmaps/mensetmanus
/usr/include/X11/bitmaps/menu10
/usr/include/X11/bitmaps/menu12
/usr/include/X11/bitmaps/menu16
/usr/include/X11/bitmaps/menu6
/usr/include/X11/bitmaps/menu8
/usr/include/X11/bitmaps/noletters
/usr/include/X11/bitmaps/opendot
/usr/include/X11/bitmaps/opendotMask
/usr/include/X11/bitmaps/plaid
/usr/include/X11/bitmaps/right_ptr
/usr/include/X11/bitmaps/right_ptrmsk
/usr/include/X11/bitmaps/root_weave
/usr/include/X11/bitmaps/scales
/usr/include/X11/bitmaps/sipb
/usr/include/X11/bitmaps/star
/usr/include/X11/bitmaps/starMask
/usr/include/X11/bitmaps/stipple
/usr/include/X11/bitmaps/target
/usr/include/X11/bitmaps/terminal
/usr/include/X11/bitmaps/tie_fighter
/usr/include/X11/bitmaps/vlines2
/usr/include/X11/bitmaps/vlines3
/usr/include/X11/bitmaps/weird_size
/usr/include/X11/bitmaps/wide_weave
/usr/include/X11/bitmaps/wingdogs
/usr/include/X11/bitmaps/woman
/usr/include/X11/bitmaps/xfd_icon
/usr/include/X11/bitmaps/xlogo11
/usr/include/X11/bitmaps/xlogo16
/usr/include/X11/bitmaps/xlogo32
/usr/include/X11/bitmaps/xlogo64
/usr/include/X11/bitmaps/xsnow
/usr/lib64/pkgconfig/xbitmaps.pc
